name: Auto Move Issues

on:
  issues:
    types: [opened, assigned, labeled, closed]

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "Backlog" when opened
        if: github.event.action == 'opened'
        run: |
          gh project issue move --project 3 --issue ${{ github.event.issue.number }} --column "Backlog"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "To-Do" when reviewed (manually move this)
        if: github.event.action == 'edited'
        run: |
          echo "Move manually after reviewing in Backlog"

      - name: Move issue to "In Progress" when assigned
        if: github.event.action == 'assigned'
        run: |
          gh project issue move --project 3 --issue ${{ github.event.issue.number }} --column "In Progress"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "In Review" when labeled as review
        if: contains(github.event.issue.labels.*.name, 'review')
        run: |
          gh project issue move --project 3 --issue ${{ github.event.issue.number }} --column "In Review"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "Done" when closed
        if: github.event.action == 'closed'
        run: |
          gh project issue move --project 3 --issue ${{ github.event.issue.number }} --column "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
